CREATE TABLE(

	ID_ARTICOLO INT,
	TITLE VARCHAR(255),
	TESTO TEXT,
	IMMAGINE VARCHAR(255),

	PRIMARY KEY(ID_ARTICOLO, TITLE)

);

CREATE TABLE ACCOUT(

	USERNAME VARCHAR(255),
	PASS VARCHAR(255),
	
	PRIMARY KEY(USERNAME)

);

CREATE TABLE PREFERITO(

	USERNAME VARCHAR(255),
	ID_ARTICOLO INT,
	TITLE VARCHAR(255),
	
	FOREIGN KEY (TITLE) REFERENCES ARTICOLO(TITLE),
	FOREIGN KEY (ID_ARTICOLO) REFERENCES ARTICOLO(ID_ARTICOLO),
	FOREIGN KEY (USERNAME) REFERENCES ACCOUT(USERNAME),
	
	PRIMARY KEY(TITLE, USERNAME, ID_ARTICOLO)

);
